# Generated by Django 4.0.5 on 2022-06-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='size_l',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Размер L'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='size_m',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Размер M'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='size_s',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Размер S'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='size_xl',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Размер XL'),
        ),
    ]
