# Generated by Django 4.0.5 on 2022-06-02 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_goods_size_l_alter_goods_size_m_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='with_sizes',
        ),
    ]
