# Generated by Django 4.0.5 on 2022-06-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_goods_with_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='client',
        ),
        migrations.RemoveField(
            model_name='order',
            name='good',
        ),
        migrations.RemoveField(
            model_name='photos',
            name='good',
        ),
        migrations.AddField(
            model_name='collections',
            name='photo',
            field=models.ImageField(blank=True, upload_to='img/collections'),
        ),
        migrations.AddField(
            model_name='goods',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Наличие'),
        ),
        migrations.AddField(
            model_name='goods',
            name='photo1',
            field=models.ImageField(blank=True, upload_to='photos/%y-%m-%d/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='goods',
            name='photo2',
            field=models.ImageField(blank=True, upload_to='photos/%y-%m-%d/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='goods',
            name='photo3',
            field=models.ImageField(blank=True, upload_to='photos/%y-%m-%d/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='goods',
            name='photo4',
            field=models.ImageField(blank=True, upload_to='photos/%y-%m-%d/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='goods',
            name='photo5',
            field=models.ImageField(blank=True, upload_to='photos/%y-%m-%d/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='goods',
            name='photo6',
            field=models.ImageField(blank=True, upload_to='photos/%y-%m-%d/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='goods',
            name='quantity',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Количество товара для не-одежды', null=True, verbose_name='Количество'),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Photos',
        ),
    ]
