# Generated by Django 4.0.5 on 2022-06-09 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_order_client_remove_order_good_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Styles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_name', models.CharField(max_length=50, verbose_name='Наименование товара')),
                ('style1', models.CharField(max_length=50, verbose_name='Название стиля 1')),
                ('style2', models.CharField(max_length=50, verbose_name='Название стиля 2')),
                ('style3', models.CharField(blank=True, max_length=50, verbose_name='Название стиля 3')),
                ('style4', models.CharField(blank=True, max_length=50, verbose_name='Название стиля 4')),
                ('style5', models.CharField(blank=True, max_length=50, verbose_name='Название стиля 5')),
                ('style6', models.CharField(blank=True, max_length=50, verbose_name='Название стиля 6')),
            ],
            options={
                'verbose_name': 'Стиль',
                'verbose_name_plural': 'Стили',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='goods',
            name='quantity',
        ),
        migrations.CreateModel(
            name='Goods_nc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(verbose_name='Описание')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена')),
                ('is_available', models.BooleanField(default=True, verbose_name='Наличие')),
                ('quantity', models.PositiveSmallIntegerField(blank=True, help_text='Количество товара для не-одежды', null=True, verbose_name='Количество')),
                ('photo1', models.ImageField(blank=True, upload_to='photos/%y-%m-%d/', verbose_name='Фото')),
                ('photo2', models.ImageField(blank=True, upload_to='photos/%y-%m-%d/', verbose_name='Фото')),
                ('photo3', models.ImageField(blank=True, upload_to='photos/%y-%m-%d/', verbose_name='Фото')),
                ('photo4', models.ImageField(blank=True, upload_to='photos/%y-%m-%d/', verbose_name='Фото')),
                ('photo5', models.ImageField(blank=True, upload_to='photos/%y-%m-%d/', verbose_name='Фото')),
                ('photo6', models.ImageField(blank=True, upload_to='photos/%y-%m-%d/', verbose_name='Фото')),
                ('collection', models.ManyToManyField(to='shop.collections', verbose_name='Коллекция')),
                ('styles', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.styles', verbose_name='Стили')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['id'],
            },
        ),
    ]
