# Generated by Django 4.0.5 on 2022-06-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_goodsnc_styles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='size_l',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='size_m',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='size_s',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='size_xl',
        ),
        migrations.AddField(
            model_name='goods',
            name='is_clothes',
            field=models.BooleanField(default=False, verbose_name='Является одеждой'),
        ),
        migrations.DeleteModel(
            name='GoodsNC',
        ),
        migrations.DeleteModel(
            name='Styles',
        ),
    ]
