# Generated by Django 4.0.5 on 2022-09-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Наименование коллекции')),
                ('slug', models.SlugField(unique=True)),
                ('photo', models.ImageField(blank=True, upload_to='img/collections')),
            ],
            options={
                'verbose_name': 'Коллекция',
                'verbose_name_plural': 'Коллекции',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена')),
                ('is_available', models.BooleanField(default=True, verbose_name='Наличие')),
                ('is_clothes', models.BooleanField(default=False, verbose_name='Является одеждой')),
                ('photo1', models.ImageField(blank=True, upload_to='photos/%y-%m-%d/', verbose_name='Фото')),
                ('photo2', models.ImageField(blank=True, upload_to='photos/%y-%m-%d/', verbose_name='Фото')),
                ('photo3', models.ImageField(blank=True, upload_to='photos/%y-%m-%d/', verbose_name='Фото')),
                ('photo4', models.ImageField(blank=True, upload_to='photos/%y-%m-%d/', verbose_name='Фото')),
                ('photo5', models.ImageField(blank=True, upload_to='photos/%y-%m-%d/', verbose_name='Фото')),
                ('photo6', models.ImageField(blank=True, upload_to='photos/%y-%m-%d/', verbose_name='Фото')),
                ('collection', models.ManyToManyField(to='shop.collections', verbose_name='Коллекция')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['id'],
            },
        ),
    ]
