# Generated by Django 4.0.5 on 2022-06-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_styles_remove_goods_quantity_goods_nc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Goods_nc',
            new_name='GoodsNC',
        ),
        migrations.AlterModelOptions(
            name='goodsnc',
            options={'ordering': ['id'], 'verbose_name': 'Товар не одежда', 'verbose_name_plural': 'Товары не одежда'},
        ),
        migrations.AlterField(
            model_name='styles',
            name='style6',
            field=models.CharField(blank=True, max_length=50, verbose_name='Название стиля 7'),
        ),
    ]
