# Generated by Django 4.0.5 on 2022-06-09 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_rename_goods_nc_goodsnc_alter_goodsnc_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsnc',
            name='styles',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.styles', verbose_name='Стили'),
        ),
    ]
